# Generated by Django 4.2.27 on 2025-12-11 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['date', 'start_time'], 'verbose_name': '最終排班', 'verbose_name_plural': '最終排班'},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_start',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='結束時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='開始時間'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='員工'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否發佈'),
        ),
    ]
