# Generated by Django 4.2.27 on 2025-12-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_sort_order'),
        ('scheduling', '0002_alter_shift_options_remove_shift_shift_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.userprofile')),
            ],
            options={
                'verbose_name': '員工可上班時段',
                'verbose_name_plural': '員工可上班時段',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
