# Generated by Django 4.2.27 on 2026-01-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userprofile_role_alter_workerdocument_category'),
        ('scheduling', '0012_schedulingwindow_break_rules_shift_break_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role__in': ['worker', 'supervisor']}, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='員工'),
        ),
    ]
