# Generated by Django 4.2.27 on 2025-12-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_schedulingwindow_allow_worker_register'),
        ('users', '0008_userprofile_emergency_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='primary_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_workers', to='scheduling.store', verbose_name='店別'),
        ),
    ]
