# Generated by Django 4.2.27 on 2025-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_primary_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdocument',
            name='category',
            field=models.CharField(choices=[('id_card_front', '身分證正面'), ('id_card_back', '身分證反面'), ('driver_license', '駕照'), ('bankbook', '存摺')], max_length=20),
        ),
    ]
