# Generated by Django 4.2.27 on 2026-01-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_salary_slip_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('worker', '員工'), ('manager', '店長'), ('supervisor', '主管')], default='worker', max_length=10),
        ),
        migrations.AlterField(
            model_name='workerdocument',
            name='category',
            field=models.CharField(choices=[('id_card_front', '身分證正面'), ('id_card_back', '身分證反面'), ('driver_license', '駕照'), ('bankbook', '存摺'), ('other', '其他')], max_length=20),
        ),
    ]
