# Generated by Django 4.2.27 on 2025-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillRangeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='workavailability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='workavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workavailability',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workavailability',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
